server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhsot:8848  # Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080  # 配置sentinel dashboard地址
        port: 8719 # 默认8719端口,假如被占用会自动从8719开始一次+1扫描,直至找到未被占用的端口

management:      # 监控
  endpoints:
    web:
      exposure:
        include: '*'